Add serialization
lightsoutgames/bevy_input_actionmap pull request #15
Opened 2022-01-20 13:15 UTC by Ygg01

Adds serialization for `bevy_input_action` by implementing a custom serializer for `inputMap.actions`. As far as I understand that is the only thing that needs serialization when preserving configuration.

Contains some minor nits.
- Upgrades examples to `bevy 0.6.0`
- Adds serialization test
- Adds serialization examples

2022-01-20 16:31 UTC, ndarilek requested changes
Thanks a bunch! Here are some questions/suggested changes:

2022-01-20 16:31 UTC, ndarilek commented on src/serialize.rs
> +#[cfg(feature = "serialize")]
Same.

2022-01-20 16:31 UTC, ndarilek commented on src/serialize.rs
> +#[cfg(feature = "serialize")]
Same.

2022-01-20 16:31 UTC, ndarilek commented on src/lib.rs
> +pub use serde::{Deserialize, Deserializer, Serialize, Serializer};
Does this need to be `pub`?

2022-01-20 16:31 UTC, ndarilek commented on src/lib.rs
>  pub struct Binding {
Does this need to be `pub` or would `pub(crate)` work??

2022-01-20 16:31 UTC, ndarilek commented on src/lib.rs
>  pub struct Action {
Likewise, `pub(crate)` here?

2022-01-20 16:31 UTC, ndarilek commented on src/lib.rs
> +    pub bindings: Vec<Binding>,
And `pub(crate)` here as well?

2022-01-20 16:31 UTC, ndarilek commented on src/lib.rs
>  pub struct InputMap<T> {
And `pub(crate)` here too?

2022-01-20 16:31 UTC, ndarilek commented on src/lib.rs
> +    pub actions: HashMap<T, Action>,
And `pub(crate)` here as well?

2022-01-21 12:00 UTC, Ygg01 commented on src/lib.rs
>  pub enum GamepadAxisDirection {
What do you mean? `GamepadAxisDirection` is already `pub` on master?

2022-01-21 12:19 UTC, Ygg01 commented on src/lib.rs
>  pub struct InputMap<T> {
Not sure what you mean here either

2022-01-21 12:20 UTC, Ygg01 commented on src/lib.rs
>  pub struct Action {
You mean the `bindings`, right?

2022-01-26 12:34 UTC, Ygg01 commented
@ndarilek updates?

2022-01-27 16:40 UTC, merged

2022-01-27 16:40 UTC, ndarilek commented
Thanks, merged!